config/routes.rb
Bookmark::Application.routes.draw do
  devise_for :admins

  resources :locations

  resources :mymarks

  devise_for :users
  devise_for :admins

  resources :marks

  root :to => "mymarks#index"

end

app/models/mark.rb
class Mark < ActiveRecord::Base
	has_many :mymarks
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController

before_filter :authenticate_user!
before_filter :authenticate_admin!, :only => [:edit, :destroy, :new]

  # GET /marks
  # GET /marks.xml
  def index
    @marks = Mark.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @marks }
    end
  end

  # GET /marks/1
  # GET /marks/1.xml
  def show
    @mark = Mark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mark }
    end
  end

  # GET /marks/new
  # GET /marks/new.xml
  def new
    @mark = Mark.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mark }
    end
  end

  # GET /marks/1/edit
  def edit
    @mark = Mark.find(params[:id])
  end

  # POST /marks
  # POST /marks.xml
  def create
    @mark = Mark.new(params[:mark])

    respond_to do |format|
      if @mark.save
        format.html { redirect_to(@mark, :notice => 'Mark was successfully created.') }
        format.xml  { render :xml => @mark, :status => :created, :location => @mark }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /marks/1
  # PUT /marks/1.xml
  def update
    @mark = Mark.find(params[:id])

    respond_to do |format|
      if @mark.update_attributes(params[:mark])
        format.html { redirect_to(@mark, :notice => 'Mark was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.xml
  def destroy
    @mark = Mark.find(params[:id])
    @mark.destroy

    respond_to do |format|
      format.html { redirect_to(marks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/marks/_form.html.erb
<%= form_for(@mark) do |f| %>
  <% if @mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
      <% @mark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marks/edit.html.erb
<h1>Editing mark</h1>

<%= render 'form' %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<h1>Listing marks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @marks.each do |mark| %>
  <tr>
    <td><a rel="nofollow" href="http://<%= mark.url %>"><%= mark.name %></a></td>
    <td><%= mark.url %></td>
    <td><%= link_to 'Show', mark %></td>
<% if admin_signed_in? %>
    <td><%= link_to 'Edit', edit_mark_path(mark) %></td>
    <td><%= link_to 'Destroy', mark, :confirm => 'Are you sure?', :method => :delete %></td>
<% end %>
  </tr>
<% end %>
</table>

<br />
<% if admin_signed_in? %>
<%= link_to 'New Mark', new_mark_path %>
<% end %>

app/views/marks/new.html.erb
<h1>New mark</h1>

<%= render 'form' %>

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mark.name %>
</p>

<p>
  <b>Url:</b>
  <%= @mark.url %>
</p>


<%= link_to 'Edit', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>