config/routes.rb
Bookmark::Application.routes.draw do
  devise_for :admins

  resources :locations

  resources :mymarks

  devise_for :users
  devise_for :admins

  resources :marks

  root :to => "mymarks#index"

end

app/models/mymark.rb
class Mymark < ActiveRecord::Base
	belongs_to :mark
	belongs_to :user
end

app/controllers/mymarks_controller.rb
class MymarksController < ApplicationController
before_filter :authenticate_user!
  # GET /mymarks
  # GET /mymarks.xml
  def index
puts params[:show_location]
if defined? params[:show_location]
    if params[:show_location]
	#set a cookie
	if params[:show_location].to_s=="all"	
		params[:show_location]=nil
		cookies[:show_location]=nil
	else
		cookies[:show_location]=params[:show_location]
	end
    end
end

if defined? params[:show_location]
	#if no params, check if cookie exists
	if cookies[:show_location]
		params[:show_location]=cookies[:show_location]
	end
end

if defined? params[:show_location]
    if params[:show_location]
	if params[:show_location].to_i == 0
		@mymarks = Mymark.find_all_by_user_id(current_user.id)
	else
		@mymarks = Mymark.find_all_by_user_id_and_location_id(current_user.id, params[:show_location])
	end
    else
	@mymarks = Mymark.find_all_by_user_id(current_user.id)
    end    
else
    @mymarks = Mymark.find_all_by_user_id(current_user.id)
end

    @locations = Location.find_all_by_user_id(current_user.id)
    if @locations.count == 0
      @location = Location.new
      @location.name = "Home"
      @location.user_id = current_user.id
      @location.save
      @location = Location.new
      @location.name = "Work"
      @location.user_id = current_user.id
      @location.save
      @locations = Location.find_all_by_user_id(current_user.id)
    end
@current_location = Location.find_by_id(params[:show_location])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mymarks }
    end
  end

  # GET /mymarks/1
  # GET /mymarks/1.xml
  def show
    @mymark = Mymark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mymark }
    end
  end

  # GET /mymarks/new
  # GET /mymarks/new.xml
  def new
    @marks=Mark.all
    @locations = Location.find_all_by_user_id(current_user.id)
    @mymark = Mymark.new
    @mymark.user_id = current_user.id
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mymark }
    end
  end

  # GET /mymarks/1/edit
  def edit
    @mymark = Mymark.find(params[:id])
    @locations = Location.find_all_by_user_id(current_user.id)
  end

  # POST /mymarks
  # POST /mymarks.xml
  def create
    @marks=Mark.all
    @locations = Location.find_all_by_user_id(current_user.id)
    @mymark = Mymark.new(params[:mymark])
    #force the user_id to the current user, so they can't do crazy stuff in the form.
    @mymark.user_id=current_user.id

    #before we do anything with the mark, clean it up
    params[:mymark][:mark_id]= params[:mymark][:mark_id].strip
    params[:mymark][:mark_id]=params[:mymark][:mark_id].gsub("http://", "")
    #ok, this could get complicated. take params[:mymark.mark_id] (which is actually the url)
    #see if it exists. If so, replace mark_id with the id, otherwise create it, then replace it.
    @mark=Mark.find_by_url(params[:mymark][:mark_id])
    
    #if there is no @mark.id, then create a @mark
    if @mark == nil
	@mark=Mark.new
        @mark.url = params[:mymark][:mark_id]
	@mark.name = params[:mymark][:mark_id]
	@mark.save
    end
    
    #finally, set the mark.id
    @mymark.mark_id=@mark.id

    respond_to do |format|
      if @mymark.save
        format.html { redirect_to(@mymark, :notice => 'Mymark was successfully created.') }
        format.xml  { render :xml => @mymark, :status => :created, :location => @mymark }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mymark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mymarks/1
  # PUT /mymarks/1.xml
  def update
    @mymark = Mymark.find(params[:id])
    @locations = Location.find_all_by_user_id(current_user.id)
    respond_to do |format|
      if @mymark.update_attributes(params[:mymark])
        format.html { redirect_to(@mymark, :notice => 'Mymark was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mymark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mymarks/1
  # DELETE /mymarks/1.xml
  def destroy
    @mymark = Mymark.find(params[:id])
    @mymark.destroy

    respond_to do |format|
      format.html { redirect_to(mymarks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/mymarks_helper.rb
module MymarksHelper
end

app/views/mymarks/_form.html.erb
<%= form_for(@mymark) do |f| %>
  <% if @mymark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mymark.errors.count, "error") %> prohibited this mymark from being saved:</h2>

      <ul>
      <% @mymark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>

<div class="field">
<%= f.label "Bookmark address (do not include http://): " %>
<%= f.text_field :mark_id %>
</div>  

<div class="field">
<%= f.label :location_id %>
<%= f.select :location_id,  @locations.map {|location| [location.name, location.id]}%> - <%= link_to "Add a new Location", :controller => "locations", :action => "new" %>
</div>

<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mymarks/edit.html.erb
<h1>Editing mymark</h1>

<%= render 'form' %>

<%= link_to 'Show', @mymark %> |
<%= link_to 'Back', mymarks_path %>

app/views/mymarks/index.html.erb
<h1>Listing mymarks</h1>
Locations: <%= link_to "Add a new Location", :controller => "locations", :action => "new" %>
Currently Showing: <% if @current_location %> <%= @current_location.name %> <% else %> All <% end %>
<ul>
<li><%= link_to "All", :controller => "mymarks", :action => "index", :show_location => "all"%></li>
<% @locations.each do |location| %>
	<li><%= link_to location.name, :controller => "mymarks", :action => "index", :show_location => location.id %></li>
<% end %>
</ul>

<P>
<table>
  <tr>
    <th>Bookmarks</th>
    <th></th>
    <th></th>
  </tr>
<tr>
<% @mymarks.each do |mymark| %>
    <td><a rel="nofollow" href="http://<% if mymark.mark_id != 0 %><%= mymark.mark.url %>"><%= mymark.mark.name %><% end %></a></td>
    <td><%= link_to 'Show', mymark %></td>
    <td><%= link_to 'Edit', edit_mymark_path(mymark) %></td>
    <td><%= link_to 'Destroy', mymark, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</p>
<br />
<%= link_to 'Add a New Bookmark', new_mymark_path %>

app/views/mymarks/new.html.erb
<h1>New mymark</h1>

<%= render 'form' %>

<%= link_to 'Back', mymarks_path %>

app/views/mymarks/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>User:</b>
  <%= @mymark.user_id %>
</p>

<p>
  <b>Mark:</b>
  <%= @mymark.mark_id %>
</p>


<%= link_to 'Edit', edit_mymark_path(@mymark) %> |
<%= link_to 'Back', mymarks_path %>